### PR TITLE
FontAwesome 5.2

### PR DESCRIPTION
**Pull request by padarom**
[FontAwesome 5.2 just released!](https://fontawesome.com/changelog/latest)

### CODE REVIEW

**Comment by rafiki270** [comment]
@padarom do you want to do a 1.4.0 release?

**Comment by padarom** [comment]
Not sure if bumping minor versions for new FontAwesome releases is the best way with CocoaPods/SemVer. I would probably prefer a 1.3.1 release and reserve 1.4 to changes to this library's API.

FontAwesome itself doesn't follow Semantic Versioning, so it's not 100% translatable.

If you agree I can draft a new release and bump the podspec version. Does anything special need to be done to update the published CocoaPods spec? I noticed it's still sitting at 1.2.

**Comment by rafiki270** [comment]
@padarom yep, makes sense :)

**Comment by rafiki270** [comment]
there was a problem updating it not sure what was the issue ... might have been xcode 10 ... will check again tomorrow

**Comment by padarom** [comment]
I'm having no issues building it for iOS, macOS, tvOS and watchOS. My two iOS projects using it both still work fine. I'll wait until you get back before drafting a release.

**Pull request merged**
