### PR TITLE
Fixes crash on loading fonts since FA 5.7.x

### PR DESCRIPTION
**Pull request by ghowen**
- Fixes crash while loading fonts as FontAwesome 5.7 introduced a breaking change in the font member names
- Update enums to 5.7.2

### CODE REVIEW

**Comment by ghowen** [comment]
Love to. What do I need to do to release? Just change the version in the .podspec and create another PR? 

For some reason cocoapods is still delivering the FA 5.5 fonts so something must have gone wrong with the 5.6 release. So I just want to get it right ;) 

Thanks!

**Comment by rafiki270** [comment]
yeah, that's it ... no idea what the issue with fonts might be ... have you cleared your xcode cache? Derived Data?

**Comment by ghowen** [comment]
Must be something with Cocoapods. They still show 2.0.1 as the most recent one although 2.0.2 should be there: https://github.com/CocoaPods/Specs/tree/master/Specs/e/b/d/AwesomeEnum. 
Do you need to tell Cocoapods somehow about an update or tag a release or something?

**Comment by ghowen** [comment]
OK, there are a few more steps involved https://sebastiandobrincu.com/blog/how-to-update-your-cocoapods-library-version and I am not sure if I have enough privileges to do them.

**Comment by ghowen** [comment]
OK, I did everything I can (I think) but I do not have the privileges to push. This must be done by @rafiki270 or @padarom.

**Comment by padarom** [comment]
I tried pushing, but I get this error:

```
λ pod trunk push AwesomeEnum.podspec
Updating spec repo `master`
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 14271 and retry the command.

CocoaPods 1.7.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.beta.1

Validating podspec
 -> AwesomeEnum (2.1.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

[!] The spec did not pass validation, due to 1 error.
```

Building in Xcode is no problem though.

**Comment by rafiki270** [comment]
Hi Georg, could you please contact me on LiveUI slack so I can sort out access to the cocoapods for you too?

**Comment by ghowen** [comment]
@padarom Hm, works for me with the exception of the missing privileges

```
CocoaPods 1.7.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.beta.1

Validating podspec
 -> AwesomeEnum (2.1.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

[!] You (xxx@xxx.xx) are not allowed to push new versions for this pod. The owners of this pod are xxx.xxx@xxx.xx and xx@xx.xx.

```

Or maybe I did not get far enough to receive that error message.

@rafiki270 I am on the LiveUI slack now and wrote something in the help channel. I am not so familiar with Slack yet so I hope this is good enough?

**Comment by ghowen** [comment]
@padarom Pushing worked for me now with the new privileges, so 2.1.0 is live on Cocoapods now.

**Comment by padarom** [comment]
Mhh odd, then maybe my toolchain isn't functional currently.

**Pull request merged**
