### PR TITLE
Raised version to 2.0.0 in podspec

### PR DESCRIPTION
**Pull request by ghowen**
Not sure if there is anything else to do. Will now test to pull in this pod directly from the repo.

### CODE REVIEW

**Comment by padarom** [comment]
Might want to wait for #30 to be merged so it can be included in 2.0.0

**Comment by rafiki270** [comment]
@padarom @ghowen need to give you guys access to the pod, could you find out how can I do that? :)

**Comment by rafiki270** [comment]
oh and yeah, if you could merge the 5.5, create a release ... it's three of us now, no need to wait for my approval :)

**Comment by padarom** [comment]
@rafiki270 https://guides.cocoapods.org/making/getting-setup-with-trunk.html

```
pod trunk add-owner ARAnalytics kyle@cocoapods.org
```
My CocoaPods trunk email is `github@padarom.io`

**Comment by padarom** [comment]
Didn't realize there's already a release/tag on GitHub for 2.0. The FA5.5 update will live in its own release then.

**Pull request merged**
